### ISSUE TITLE
application.py import uvloop can't run in windows 10

### ISSUE THREAD

**Issue by pytomtoto** [songtao-git/wings-sanic#1]
```
python 3.7
sanic 18.12.0
wings-sanic 0.5.18
```
application.py中使用了uvloop 希望能和sanic一样有脱离这些库，运行在windows上做开发。
就像这样SANIC_NO_UVLOOP=true SANIC_NO_UJSON=true pip3 install sanic
```
try:
    import uvloop

    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
except ImportError:
    pass
```

**Comment by songtao-git** [comment]
Thank you for your valuable advice. The issue has been fixed in 0.5.19.
