### ISSUE TITLE
delete请求成功响应为空

### ISSUE THREAD

**Issue by ymb1991** [songtao-git/wings-sanic#3]
如何让delete请求成功后返回前端的response中的content不为空

**Comment by songtao-git** [comment]
有两种方式：
1. 直接返回你希望返回的json文档，比如{"id": 1}。这种情况下如果定义了response_serializer, 会按照对应格式来处理。
2. 返回sanic.response.BaseHTTPResponse子类的实例。Response内可以任意定义，即使不是application/json格式都可以。这种情况不会根据response_serializer格式处理，而是直接返回你 写好的Response实例
